name: Purge and Warm jsDelivr Cache

on:
  push:
    paths:
      - "data/**"

jobs:
  purge-and-warm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Purge jsDelivr cache
        run: |
          REPO=${{ github.repository }}

          for file in $(find data -type f); do
            PURGE_URL="https://purge.jsdelivr.net/gh/$REPO/$file"
            echo "Purging $PURGE_URL"
            curl -s "$PURGE_URL"
          done

      - name: Warm jsDelivr cache
        run: |
          REPO=${{ github.repository }}

          for file in $(find data -type f); do
            CDN_URL="https://cdn.jsdelivr.net/gh/$REPO/$file"
            echo "Warming $CDN_URL"
            curl -s -A "cdn-cache-warmer" -o /dev/null "$CDN_URL"
          done
